### ISSUE TITLE
Solr recipe needs upgraded dev-libs/nss package

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cookbooks-stable-v5#261]
The Solr recipe fails with this error:

```
Expected process to exit with [0], but received '1'
^[[0m---- Begin output of sleep 30 && /data/solr/bin/solr create_core -c default ----
^[[0mSTDOUT:
^[[0mSTDERR: Exception in thread "main" java.lang.InternalError
^[[0m   at sun.security.ec.SunEC.initialize(Native Method)
^[[0m   at sun.security.ec.SunEC.access$000(SunEC.java:49)
^[[0m   at sun.security.ec.SunEC$1.run(SunEC.java:61)
^[[0m   at sun.security.ec.SunEC$1.run(SunEC.java:58)
```

due to this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1332456

I manually upgraded `dev-libs/nss` to version 3.23 and `/data/solr/bin/solr create_core -c default` worked after that.

Please update the recipe to install the `dev-libs/nss` version 3.23 before installing Solr.

**Comment by radamanthus** [comment]
Fixed in https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.33
